  - name: create user
    tags: always
    ansible.builtin.user:
      name: simone
      group: root

  - name: add sudoers file for simone
    tags: always
    ansible.builtin.copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

  - name: add ssh key for simone
    tags: always
    ansible.builtin.authorized_key:
      user: simone
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKYXUmZz1TMf3Htm12O2Z9gFS6eWhK2vF1Wha7Qi3kQz trey@ubuntu-ws
